/**
 * Checklist items for the left column.
 */
const CHECKLIST = [
  'Workfront project auto-creates with tasks for each deliverable',
  'Product hero image generated by Google Imagen',
  'Product page created in DA.live via EDS Admin API',
  'Blog article auto-drafted from product description',
  'PDF brochure generated from product content',
  'All tasks assigned with review and approval routing',
];

const CHECK_SVG = '<svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round"><path d="M20 6L9 17l-5-5"/></svg>';
const SEND_SVG = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M22 2L11 13"/><path d="M22 2l-7 20-4-9-9-4z"/></svg>';

/**
 * Adobe I/O Runtime proxy URL.
 * Proxies form payload to Fusion webhook with Basic Auth (credentials hidden server-side).
 * Set to empty string to fall back to demo mode (simulated).
 *
 * Deploy: aio rt action create create-page-proxy --kind nodejs:18 --web true create-page-proxy.js
 * Then: aio rt action get create-page-proxy --url
 */
const WORKER_URL = 'https://23750-539copperbadger.adobeioruntime.net/api/v1/web/default/create-page-proxy';

/**
 * Builds the form card HTML.
 * Each input has a data-field attribute for payload extraction.
 * @returns {string}
 */
function buildFormHTML() {
  return `
    <div class="form-card sr sr-d2">
      <div class="launch-form-inner">
        <div class="fg">
          <label>Product Name <span class="req">*</span></label>
          <input type="text" class="fi" data-field="productName" value="Pulse" required>
        </div>
        <div class="fg">
          <label>Tagline <span class="req">*</span></label>
          <input type="text" class="fi" data-field="tagline" value="Real-time visibility into every integration">
        </div>
        <div class="fg">
          <label>Product Description <span class="req">*</span></label>
          <textarea class="ft" data-field="description" rows="3">AI-powered integration monitoring platform that gives enterprise IT teams real-time visibility into every API, webhook, and data flow across their technology stack.</textarea>
        </div>
        <div class="fg">
          <label>Key Features <span class="req">*</span> <span class="hint">(comma separated)</span></label>
          <input type="text" class="fi" data-field="features" value="Real-time Dashboard, Smart Alerts, Health Scores, Audit Trail">
        </div>
        <div class="fg">
          <label>Target Audience <span class="req">*</span></label>
          <select class="fs" data-field="audience" required>
            <option disabled>Select audience</option>
            <option selected>Enterprise IT Teams</option>
            <option>Marketing Teams</option>
            <option>Content Operations</option>
            <option>DevOps</option>
          </select>
        </div>
        <div class="fg">
          <label>Requested By <span class="req">*</span></label>
          <input type="text" class="fi" data-field="requestedBy" value="Shravan Bachu">
        </div>
        <button type="button" class="btn-submit" id="btnLaunch">
          ${SEND_SVG}
          Launch Product
        </button>
      </div>
    </div>
  `;
}

/**
 * Collects form field values using data-field attributes.
 * @param {Element} container The form container element
 * @returns {object} Form payload
 */
function collectFormData(container) {
  const payload = {};
  container.querySelectorAll('[data-field]').forEach((el) => {
    payload[el.getAttribute('data-field')] = el.value.trim();
  });
  return payload;
}

/**
 * Sends payload to the Cloudflare Worker proxy.
 * @param {object} payload Form data
 * @returns {Promise<object>} Response from worker
 */
async function submitToWorker(payload) {
  const resp = await fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({ error: resp.statusText }));
    throw new Error(err.error || `HTTP ${resp.status}`);
  }
  return resp.json();
}

/**
 * Sets button state (text, color, disabled).
 * @param {Element} btn Button element
 * @param {string} html Inner HTML
 * @param {string} bg Background CSS value (empty to reset)
 * @param {boolean} disabled Whether button is disabled
 */
function setBtnState(btn, html, bg, disabled) {
  btn.innerHTML = html;
  btn.style.background = bg;
  btn.style.opacity = disabled ? '0.6' : '1';
  btn.disabled = disabled;
}

/**
 * Decorates the launch block.
 * Expects authored rows:
 *   Row 0: label text
 *   Row 1: heading (H2) — may contain gradient-text via <em>
 *   Row 2: subtitle paragraph
 * Form and checklist are auto-generated.
 * @param {Element} block The launch block element
 */
export default function decorate(block) {
  const rows = [...block.children];

  block.id = 'launch';
  block.setAttribute('role', 'region');
  block.setAttribute('aria-label', 'Launch a Product');

  const labelRow = rows[0];
  const headingRow = rows[1];
  const subtitleRow = rows[2];

  const labelText = labelRow ? labelRow.textContent.trim() : 'Try It Live';
  const headingEl = headingRow ? headingRow.querySelector('h1, h2, h3') : null;
  const headingHTML = headingEl
    ? headingEl.outerHTML
    : '<h2>Launch a product \u2014 <span class="gradient-text">right now.</span></h2>';
  const subtitleText = subtitleRow ? subtitleRow.textContent.trim() : '';

  const checklistHTML = CHECKLIST.map((item) => `
    <div class="launch-item">
      <div class="launch-check">${CHECK_SVG}</div>
      ${item}
    </div>
  `).join('');

  block.textContent = '';
  block.innerHTML = `
    <div class="sr">
      <span class="label">${labelText}</span>
      ${headingHTML}
      <p class="subtitle launch-subtitle">${subtitleText}</p>
    </div>
    <div class="launch-grid">
      <div class="launch-info sr sr-d1">
        <h3>Submit your product details. Content Workflow handles everything else.</h3>
        <p>One form submission triggers the entire content lifecycle. No manual page creation. No Workfront ticket filing. No chasing approvals.</p>
        <div class="launch-list">${checklistHTML}</div>
      </div>
      ${buildFormHTML()}
    </div>
  `;

  const btn = block.querySelector('#btnLaunch');
  if (!btn) return;

  const originalHTML = btn.innerHTML;

  btn.addEventListener('click', async () => {
    if (btn.disabled) return;

    const payload = collectFormData(block);

    // Validate required fields
    if (!payload.productName || !payload.description) {
      setBtnState(btn, '\u26A0 Please fill all required fields', 'var(--red)', false);
      setTimeout(() => setBtnState(btn, originalHTML, '', false), 2500);
      return;
    }

    setBtnState(btn, '\u23F3 Creating assets via Fusion...', '', true);

    // Live mode — POST to Cloudflare Worker
    if (WORKER_URL) {
      try {
        const result = await submitToWorker(payload);
        /* eslint-disable-next-line no-console */
        console.log('[ContentFlow] Launch result:', result);

        // Show success panel with links
        const formInner = block.querySelector('.launch-form-inner');
        if (formInner && result.workfrontURL) {
          formInner.innerHTML = `
            <div class="launch-success">
              <div class="launch-success-icon">✓</div>
              <h3>${payload.productName} launch initiated</h3>
              <p>Your product page, article, and brochure are being created. The Workfront project is ready for tracking.</p>
              <div class="launch-success-links">
                <a href="${result.workfrontURL}" target="_blank" rel="noopener" class="launch-link launch-link-wf">
                  <span class="launch-link-icon">📋</span>
                  <span>
                    <strong>Open in Workfront</strong>
                    <small>Track project, review & approve</small>
                  </span>
                  <span class="launch-link-arrow">→</span>
                </a>
                <a href="${result.daPageURL}" target="_blank" rel="noopener" class="launch-link launch-link-da">
                  <span class="launch-link-icon">✏️</span>
                  <span>
                    <strong>Edit in DA.live</strong>
                    <small>Review & author the product page</small>
                  </span>
                  <span class="launch-link-arrow">→</span>
                </a>
                <a href="${result.previewURL}" target="_blank" rel="noopener" class="launch-link launch-link-preview">
                  <span class="launch-link-icon">👁️</span>
                  <span>
                    <strong>Preview Page</strong>
                    <small>See the live preview on EDS</small>
                  </span>
                  <span class="launch-link-arrow">→</span>
                </a>
              </div>
              <button type="button" class="btn-submit btn-relaunch" id="btnRelaunch">
                ${SEND_SVG} Launch Another Product
              </button>
            </div>`;
          // Relaunch button reloads form
          block.querySelector('#btnRelaunch')?.addEventListener('click', () => {
            formInner.innerHTML = buildFormHTML().replace('<div class="form-card sr sr-d2">', '').replace(/<\/div>\s*$/, '');
            const newBtn = block.querySelector('#btnLaunch');
            if (newBtn) newBtn.addEventListener('click', btn.clickHandler);
          });
        } else {
          setBtnState(
            btn,
            `✓ ${payload.productName} launch initiated — check Workfront`,
            'var(--green)',
            false,
          );
          setTimeout(() => setBtnState(btn, originalHTML, '', false), 4000);
        }
      } catch (err) {
        setBtnState(btn, `✖ Error: ${err.message}`, 'var(--red)', false);
        /* eslint-disable-next-line no-console */
        console.error('[ContentFlow] Launch error:', err);
        setTimeout(() => setBtnState(btn, originalHTML, '', false), 4000);
      }
      return;
    }

    // Demo mode — simulated response
    setTimeout(() => {
      setBtnState(
        btn,
        `\u2713 ${payload.productName} launch initiated \u2014 check Workfront`,
        'var(--green)',
        false,
      );
      setTimeout(() => setBtnState(btn, originalHTML, '', false), 4000);
    }, 2500);
  });
}
